FROM node:25.1.0-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PUPPETEER_SKIP_DOWNLOAD=true

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends chromium && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install --omit=dev && npm cache clean --force

COPY src/ ./src/

RUN mkdir -p /app/auth /app/logs

CMD ["npm", "start"]